/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pantallas;

import gestores.GestorProducto; // Las pantallas se comunican con la logica de negocio no les interesa como llegan los datos 
import java.awt.Desktop;
import java.awt.Image;
import java.awt.MediaTracker;
import java.awt.event.KeyEvent;
import java.io.*;
import static java.lang.Float.parseFloat;
import static java.lang.Integer.parseInt;
import static java.lang.Long.parseLong;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author German
 */
public class AltaProducto extends javax.swing.JFrame {

    /**
     * Creates new form AltaProducto
     */
    public AltaProducto() {

        AparienciaPantalla apa = new AparienciaPantalla();
        apa.cambiarApariencia("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TFidProducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAdescripcion = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        CBseleccionRubro = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        CBseleccionProveedor = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        TFstockProducto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TFsotckProductoMin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TFsotckProductoMax = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TFidProducto1 = new javax.swing.JTextField();
        BimprimirCodigo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TFDescuento = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TFporcentajeUtilidad1 = new javax.swing.JTextField();
        TFporcentajeUtilidad2 = new javax.swing.JTextField();
        TFporcentajeUtilidad3 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TFPrecio1 = new javax.swing.JTextField();
        TFPrecio2 = new javax.swing.JTextField();
        TFPrecio3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        RBnoComision = new javax.swing.JRadioButton();
        RBcomisionRegistroVendedor = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        TFmontoComisionProd = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        BquitarImagenProd = new javax.swing.JButton();
        BagregarImagenProd1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BagregarSustitutoProd = new javax.swing.JButton();
        BquitarSustitutoProd = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        TFprecioPromoProd = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DCpromoDesde = new com.toedter.calendar.JDateChooser();
        DCpromoHasta = new com.toedter.calendar.JDateChooser();
        Bayuda = new javax.swing.JButton();
        BguardarAltaProd = new javax.swing.JButton();
        BcancelarAltaProd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar un nuevo producto");
        setResizable(false);

        jLabel1.setText("Código del producto");

        TFidProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFidProductoFocusLost(evt);
            }
        });
        TFidProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFidProductoKeyTyped(evt);
            }
        });

        jLabel2.setText("Descripción");

        TAdescripcion.setColumns(20);
        TAdescripcion.setRows(5);
        jScrollPane1.setViewportView(TAdescripcion);

        jLabel3.setText("Rubro");

        CBseleccionRubro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Zapatos", "Zapatillas", "Zapatitos" }));

        jLabel4.setText("Proveedor");

        CBseleccionProveedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nike", "John Foos", "Pepe", "Adidas" }));

        jLabel5.setText("Existencia (cantidad actual)");

        TFstockProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFstockProductoKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad minima");

        TFsotckProductoMin.setEditable(false);

        jLabel7.setText("Cantidad máxima");

        TFsotckProductoMax.setEditable(false);

        jButton1.setText("+");

        jButton2.setText("+");

        jLabel12.setText("Código adicional");

        BimprimirCodigo.setText("Imprimir codigo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(TFstockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(TFidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TFidProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(BimprimirCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CBseleccionRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CBseleccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(TFsotckProductoMin, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFsotckProductoMax, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)
                                            .addComponent(jButton2)))))
                            .addComponent(jLabel3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TFidProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFidProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BimprimirCodigo))))
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CBseleccionRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBseleccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFstockProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TFsotckProductoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TFsotckProductoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(31, 31, 31)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("General", jPanel1);

        jLabel9.setText("Costo");

        TFDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFDescuentoFocusLost(evt);
            }
        });
        TFDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFDescuentoKeyTyped(evt);
            }
        });

        jLabel10.setText("No Incluir el IVA, el mismo será calculado en la venta.");

        jLabel13.setText("Porcentaje de utilidad");

        jLabel14.setText("Porcentaje de utilidad");

        jLabel19.setText("Porcentaje de utilidad");

        TFporcentajeUtilidad1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFporcentajeUtilidad1FocusLost(evt);
            }
        });
        TFporcentajeUtilidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFporcentajeUtilidad1KeyTyped(evt);
            }
        });

        TFporcentajeUtilidad2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFporcentajeUtilidad2FocusLost(evt);
            }
        });
        TFporcentajeUtilidad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFporcentajeUtilidad2KeyTyped(evt);
            }
        });

        TFporcentajeUtilidad3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TFporcentajeUtilidad3FocusLost(evt);
            }
        });
        TFporcentajeUtilidad3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TFporcentajeUtilidad3KeyTyped(evt);
            }
        });

        jLabel20.setText("Precio 1");

        jLabel21.setText("Precio 2");

        jLabel22.setText("Precio 3");

        TFPrecio1.setEditable(false);

        TFPrecio2.setEditable(false);

        TFPrecio3.setEditable(false);

        jLabel11.setText("Con debito");

        jLabel23.setText("Con crédito");

        jLabel24.setText("Efectivo");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(TFDescuento, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel19)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFporcentajeUtilidad2)
                            .addComponent(TFporcentajeUtilidad3)
                            .addComponent(TFporcentajeUtilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(TFporcentajeUtilidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(TFPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(TFDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TFporcentajeUtilidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(TFPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TFporcentajeUtilidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(TFPrecio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(36, 36, 36)
                .addComponent(jLabel10)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Precios", jPanel3);

        RBnoComision.setText("No usar comisión para este producto");

        RBcomisionRegistroVendedor.setText("Usar la comisión definida en el registro del vendedor");

        jLabel15.setText("Monto");

        jRadioButton1.setText("Usar un monto fijo personalizado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(RBcomisionRegistroVendedor)
                    .addComponent(RBnoComision)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(TFmontoComisionProd, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(384, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(RBnoComision)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RBcomisionRegistroVendedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(TFmontoComisionProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(316, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Comisiones", jPanel2);

        BquitarImagenProd.setText("-");
        BquitarImagenProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BquitarImagenProdActionPerformed(evt);
            }
        });

        BagregarImagenProd1.setText("+");
        BagregarImagenProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagregarImagenProd1ActionPerformed(evt);
            }
        });

        jEditorPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane4.setViewportView(jEditorPane1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 557, Short.MAX_VALUE)
                        .addComponent(BquitarImagenProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BagregarImagenProd1))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BagregarImagenProd1)
                    .addComponent(BquitarImagenProd))
                .addContainerGap(173, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Imagen", jPanel4);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Codigo", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable1);

        BagregarSustitutoProd.setText("+");

        BquitarSustitutoProd.setText("-");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BquitarSustitutoProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BagregarSustitutoProd)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BquitarSustitutoProd)
                    .addComponent(BagregarSustitutoProd))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sustitutos", jPanel5);

        jCheckBox1.setText("Activar promoción");

        jLabel16.setText("Precio de venta en promoción");

        TFprecioPromoProd.setEditable(false);

        jLabel17.setText("Desde");

        jLabel18.setText("Hasta");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFprecioPromoProd))
                .addGap(131, 131, 131)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DCpromoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(DCpromoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DCpromoDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFprecioPromoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DCpromoHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(337, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Promoción", jPanel7);

        Bayuda.setText("Ayuda");
        Bayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BayudaActionPerformed(evt);
            }
        });

        BguardarAltaProd.setText("Guardar");
        BguardarAltaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BguardarAltaProdActionPerformed(evt);
            }
        });

        BcancelarAltaProd.setText("Cancelar");
        BcancelarAltaProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BcancelarAltaProdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Bayuda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BguardarAltaProd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BcancelarAltaProd)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BcancelarAltaProd)
                    .addComponent(BguardarAltaProd)
                    .addComponent(Bayuda))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BguardarAltaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BguardarAltaProdActionPerformed
        if(validar()){
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No se ha podido agregar el nuevo producto"
                    + " \n\rrevise que los campos estén correctamente completados");
        }
    }//GEN-LAST:event_BguardarAltaProdActionPerformed

    private void BcancelarAltaProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BcancelarAltaProdActionPerformed
        this.dispose();
    }//GEN-LAST:event_BcancelarAltaProdActionPerformed

    private void TFporcentajeUtilidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFporcentajeUtilidad1KeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TFporcentajeUtilidad1KeyTyped

    private void TFporcentajeUtilidad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFporcentajeUtilidad2KeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TFporcentajeUtilidad2KeyTyped

    private void TFporcentajeUtilidad3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFporcentajeUtilidad3KeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_TFporcentajeUtilidad3KeyTyped

    private void TFporcentajeUtilidad1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFporcentajeUtilidad1FocusLost
        calcularImporte();
    }//GEN-LAST:event_TFporcentajeUtilidad1FocusLost

    private void TFporcentajeUtilidad2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFporcentajeUtilidad2FocusLost
        calcularImporte();
    }//GEN-LAST:event_TFporcentajeUtilidad2FocusLost

    private void TFporcentajeUtilidad3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFporcentajeUtilidad3FocusLost
        calcularImporte();
    }//GEN-LAST:event_TFporcentajeUtilidad3FocusLost

    private void TFDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFDescuentoFocusLost
        calcularImporte();
    }//GEN-LAST:event_TFDescuentoFocusLost

    private void TFidProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFidProductoKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_TFidProductoKeyTyped

    private void TFidProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TFidProductoFocusLost
        long evitaError = 0;
        try {
            evitaError = GestorProducto.ConsultaProducto(parseLong(TFidProducto.getText())).getCodigoDeProducto();
        }catch (NumberFormatException e){
            evitaError = 0;
        }
        if (evitaError!=0){
            JOptionPane.showMessageDialog(null, "El producto ya existe: " + GestorProducto.ConsultaProducto(parseLong(TFidProducto.getText())).getNombreProducto());
            TFidProducto.requestFocus();
        }
    }//GEN-LAST:event_TFidProductoFocusLost

    private void BagregarImagenProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagregarImagenProd1ActionPerformed
        agregarImagen();
    }//GEN-LAST:event_BagregarImagenProd1ActionPerformed

    private void BquitarImagenProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BquitarImagenProdActionPerformed
        jEditorPane1.removeAll();
        jEditorPane1.repaint();
    }//GEN-LAST:event_BquitarImagenProdActionPerformed

    private void TFDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFDescuentoKeyTyped
        char car = evt.getKeyChar();
        if (((car < '0') || (car > '9')) && (car != KeyEvent.VK_BACK_SPACE) && (car != '.')) {
            evt.consume();
        }
        if (car == '.' && TFDescuento.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_TFDescuentoKeyTyped

    private void TFstockProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TFstockProductoKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_TFstockProductoKeyTyped

    private void BayudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BayudaActionPerformed
        abrirAyuda();
    }//GEN-LAST:event_BayudaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BagregarImagenProd1;
    private javax.swing.JButton BagregarSustitutoProd;
    private javax.swing.JButton Bayuda;
    private javax.swing.JButton BcancelarAltaProd;
    private javax.swing.JButton BguardarAltaProd;
    private javax.swing.JButton BimprimirCodigo;
    private javax.swing.JButton BquitarImagenProd;
    private javax.swing.JButton BquitarSustitutoProd;
    private javax.swing.JComboBox CBseleccionProveedor;
    private javax.swing.JComboBox CBseleccionRubro;
    private com.toedter.calendar.JDateChooser DCpromoDesde;
    private com.toedter.calendar.JDateChooser DCpromoHasta;
    private javax.swing.JRadioButton RBcomisionRegistroVendedor;
    private javax.swing.JRadioButton RBnoComision;
    private javax.swing.JTextArea TAdescripcion;
    private javax.swing.JTextField TFDescuento;
    private javax.swing.JTextField TFPrecio1;
    private javax.swing.JTextField TFPrecio2;
    private javax.swing.JTextField TFPrecio3;
    private javax.swing.JTextField TFidProducto;
    private javax.swing.JTextField TFidProducto1;
    private javax.swing.JTextField TFmontoComisionProd;
    private javax.swing.JTextField TFporcentajeUtilidad1;
    private javax.swing.JTextField TFporcentajeUtilidad2;
    private javax.swing.JTextField TFporcentajeUtilidad3;
    private javax.swing.JTextField TFprecioPromoProd;
    private javax.swing.JTextField TFsotckProductoMax;
    private javax.swing.JTextField TFsotckProductoMin;
    private javax.swing.JTextField TFstockProducto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private boolean validar() {
        boolean ok=false;
        if (camposVacios()) {
            try {
                long codigoDeBarras = parseLong(TFidProducto.getText());
                int stock = parseInt(TFstockProducto.getText());
                String descripcion = TAdescripcion.getText();
                float precioCosto = Float.parseFloat(TFDescuento.getText());
                if (GestorProducto.agregarProducto(codigoDeBarras, descripcion, precioCosto, stock)){
                    agregarPreciosBD();
                }
                ok=true;
            } catch (NumberFormatException e) {
                System.out.print(e);
            }
        }
        return ok;
    }

    private boolean camposVacios() {
        boolean ok = false;
        if (TFidProducto.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "No ha ingresado ningun codigo de barra");
            TFidProducto.requestFocus();
        } else {
            if (TAdescripcion.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "No ha ingresado ninguna descripción");
                TAdescripcion.requestFocus();
            } else {
                if (TFDescuento.getText().trim().length() == 0) {
                    JOptionPane.showMessageDialog(null, "No ha ingresado el precio de costo");
                    TFDescuento.requestFocus();
                } else {
                    if (TFstockProducto.getText().trim().length() == 0) {
                        JOptionPane.showMessageDialog(null, "No ha ingresado stock inicial");
                        TFDescuento.requestFocus();
                    } else {
                        ok = true;
                    }
                }
            }
        }
        return ok;
    }
    
    private void calcularImporte(){
        try{
            float precio = (float) ((1+parseInt(TFporcentajeUtilidad1.getText())*0.01)*parseFloat(TFDescuento.getText()));
            TFPrecio1.setText(String.valueOf(precio));
        }catch (NumberFormatException e){
            TFPrecio1.setText(null);
        }
        
        try{
            float precio = (float) ((1+parseInt(TFporcentajeUtilidad2.getText())*0.01)*parseFloat(TFDescuento.getText()));
            TFPrecio2.setText(String.valueOf(precio));
        }catch (NumberFormatException e){
            TFPrecio2.setText(null);
        }
        
        try{
            float precio = (float) ((1+parseInt(TFporcentajeUtilidad3.getText())*0.01)*parseFloat(TFDescuento.getText()));
            TFPrecio3.setText(String.valueOf(precio));
        }catch (NumberFormatException e){
            TFPrecio3.setText(null);
        }
    }
    
    private void agregarPreciosBD (){
        long id = parseLong(TFidProducto.getText());
        float valor;
        if (TFPrecio1.getText().trim().length() != 0){
            valor = parseFloat(TFPrecio1.getText());
            GestorProducto.actualizarPrecio(id, 1, valor);
        }
        if (TFPrecio2.getText().trim().length() != 0){
            valor = parseFloat(TFPrecio2.getText());
            GestorProducto.actualizarPrecio(id, 2, valor);
        }
        if (TFPrecio3.getText().trim().length() != 0){
            valor = parseFloat(TFPrecio3.getText());
            GestorProducto.actualizarPrecio(id, 3, valor);
        }
    }

    private void abrirAyuda() {
        try {
            //File file = new File(System.getProperty("user.dir") + "\\src\\ayuda\\Manual_Agregar_Producto.pdf");
            //Desktop.getDesktop().open(file);
            
            if (Desktop.isDesktopSupported()) {
            File file = new File("Ayuda_Agregar_Producto.pdf");
            if (!file.exists()) {
                InputStream inputStream = ClassLoader.getSystemClassLoader()
                                    .getResourceAsStream("ayuda/Ayuda_Agregar_Producto.pdf");
                OutputStream outputStream = new FileOutputStream(file);
                byte[] buffer = new byte[1024];
                int length;
                while ((length = inputStream.read(buffer)) > 0) {
                    outputStream.write(buffer, 0, length);
                }
                outputStream.close();
                inputStream.close();
            }
            Desktop.getDesktop().open(file);
            }
            
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "No se puedo abrir el archivo de ayuda");
        }
    }

    private String agregarImagen() {
        JFileChooser selector=new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG, JPEG", "jpg", "jpeg");
        
        selector.setFileFilter(filtro);
        
        int estado=selector.showOpenDialog(null);
        File archivoelegido;
        String ruta = "";
        JLabel etiqueta;
        
        if(estado==JFileChooser.APPROVE_OPTION){
            archivoelegido=selector.getSelectedFile();
            ruta=archivoelegido.getPath();
        
            ImageIcon imagen = new ImageIcon(ruta);
            if(imagen.getImageLoadStatus()!=MediaTracker.COMPLETE){
                JOptionPane.showMessageDialog(null, "Seleccione un tipo de archivo válido");
            }else{
                System.out.println("Se cargo");
                etiqueta = new JLabel(imagen);
                etiqueta.setBounds(200,0,250,250);
                /**/
                Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(etiqueta.getWidth(), etiqueta.getHeight(), Image.SCALE_DEFAULT));
                etiqueta.setIcon(icono);
                this.repaint();
                /**/
                jEditorPane1.removeAll();
                jEditorPane1.add(etiqueta);
                if(archivoelegido.exists()){
                    System.out.println("bien");
                }else{
                    System.out.println("no bien");
                }
            }
        }
    return ruta;
    }
}
