/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

import entidades.Cliente;
import gestores.GestorPago;
import static java.lang.Float.parseFloat;
import static java.lang.String.valueOf;
import static java.lang.String.valueOf;
import static java.lang.String.valueOf;
import javax.swing.JOptionPane;


/**
 *
 * @author Administrador
 */
public class MedioDePago extends javax.swing.JPanel {

    /**
     * Creates new form MedioDePago
     */
    public MedioDePago() {
        initComponents();
        valoresIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtImporte = new javax.swing.JLabel();
        intPago = new javax.swing.JTextField();
        txtResultado = new javax.swing.JLabel();
        intResultado = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MontoAPagar = new javax.swing.JTextField();
        bCalcular = new javax.swing.JButton();

        txtImporte.setText("pideIngresoDeImporte");

        intPago.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtResultado.setText("resultadoOperacion");

        intResultado.setEditable(false);

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("El importe a pagar por el cliente es de:");

        MontoAPagar.setEditable(false);
        MontoAPagar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        MontoAPagar.setText("MontoAPagar");

        bCalcular.setText("Calcular");
        bCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtImporte))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(txtResultado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(132, 132, 132)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(intResultado)
                                    .addComponent(intPago)
                                    .addComponent(bCalcular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(MontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(MontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(txtImporte)
                .addGap(21, 21, 21)
                .addComponent(intPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(txtResultado)
                .addGap(21, 21, 21)
                .addComponent(intResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bCalcular)
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCalcularActionPerformed
        operar();
    }//GEN-LAST:event_bCalcularActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        confirmarPago();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MontoAPagar;
    private javax.swing.JButton bCalcular;
    private javax.swing.JTextField intPago;
    private javax.swing.JTextField intResultado;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtImporte;
    private javax.swing.JLabel txtResultado;
    // End of variables declaration//GEN-END:variables
    public Cliente c;
    public float montoAPagar;
    public int medioDePago;

    private void valoresIniciales() {
        switch (medioDePago){
            case 0: //efectivo
                txtImporte.setText("Ingrese pago realizado por el cliente: ");
                MontoAPagar.setText(valueOf(montoAPagar));
                txtResultado.setText("El vuelto correspondiente al pago: ");
                break;
            default:
                break;
        }
    }

    private void operar() {
        String resultado = "";
        if (parseFloat(intPago.getText())<=montoAPagar){
            resultado = valueOf(parseFloat(intPago.getText())-montoAPagar);
        }else{
            JOptionPane.showMessageDialog(bCalcular, "El importe ingresado es menor al monto a abonar", 
                    "Pago", JOptionPane.INFORMATION_MESSAGE);
        }
        intResultado.setText(resultado);
    }

    private void confirmarPago() {
        switch (medioDePago){
            case 0: // efectivo
                if (c.getIdCliente()!=0){
                    float pagoRealizado=parseFloat(intPago.getText());
                    GestorPago.ingresarPago(c.getIdCliente(), pagoRealizado, 1);
                }else{
                    
                }
                break;
                
            default:
                break;
        }
    }
    
    

}
