/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

/**
 *
 * @author Ema
 */
public class MenuDeOpcionesAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeOpcionesAdministrador
     */
    public MenuDeOpcionesAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CerrarSesionAdministrador = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        GestionDeUsuarioAministrador = new javax.swing.JMenu();
        altaUsuarioMenuItem = new javax.swing.JMenuItem();
        modificarUsuarioMenuItem = new javax.swing.JMenuItem();
        borraUsuarioMenuItem = new javax.swing.JMenuItem();
        backUPMenu = new javax.swing.JMenu();
        realizarBackUPMenuItem = new javax.swing.JMenuItem();
        levantarBackUPMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Opciones del Administrador");
        setExtendedState(MenuDeOpcionesAdministrador.MAXIMIZED_BOTH);

        CerrarSesionAdministrador.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CerrarSesionAdministrador.setText("Cerrar Sesion");

        GestionDeUsuarioAministrador.setText("Gestion de Usuarios");

        altaUsuarioMenuItem.setText("Alta Usuario");
        altaUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaUsuarioMenuItemActionPerformed(evt);
            }
        });
        GestionDeUsuarioAministrador.add(altaUsuarioMenuItem);

        modificarUsuarioMenuItem.setText("Modificar Privilegios");
        GestionDeUsuarioAministrador.add(modificarUsuarioMenuItem);

        borraUsuarioMenuItem.setText("Eliminar Usuario");
        GestionDeUsuarioAministrador.add(borraUsuarioMenuItem);

        jMenuBar1.add(GestionDeUsuarioAministrador);

        backUPMenu.setText("BackUp");

        realizarBackUPMenuItem.setText("Hacer BackUp");
        backUPMenu.add(realizarBackUPMenuItem);

        levantarBackUPMenuItem.setText("Abrir BackUp");
        backUPMenu.add(levantarBackUPMenuItem);

        jMenuBar1.add(backUPMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(467, Short.MAX_VALUE)
                .addComponent(CerrarSesionAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(CerrarSesionAdministrador)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_altaUsuarioMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeOpcionesAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CerrarSesionAdministrador;
    private javax.swing.JMenu GestionDeUsuarioAministrador;
    private javax.swing.JMenuItem altaUsuarioMenuItem;
    private javax.swing.JMenu backUPMenu;
    private javax.swing.JMenuItem borraUsuarioMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem levantarBackUPMenuItem;
    private javax.swing.JMenuItem modificarUsuarioMenuItem;
    private javax.swing.JMenuItem realizarBackUPMenuItem;
    // End of variables declaration//GEN-END:variables
}
