/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pantallas;

/**
 *
 * @author Ema
 */
public class MenuDeOpcionesDueño extends javax.swing.JFrame {

    /**
     * Creates new form MenuDeOpcionesDueño
     */
    public MenuDeOpcionesDueño() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CerrarSesionDueño = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        GestionDeClientes = new javax.swing.JMenu();
        AltaCliente = new javax.swing.JMenuItem();
        ClientesCtaCte = new javax.swing.JMenuItem();
        ClientesMorosos = new javax.swing.JMenuItem();
        BajaCliente = new javax.swing.JMenuItem();
        GestionDeProductos = new javax.swing.JMenu();
        AltaProducto = new javax.swing.JMenuItem();
        ModificarProducto = new javax.swing.JMenuItem();
        OperacionesDiarias = new javax.swing.JMenu();
        ArqueosYCierresDeCaja = new javax.swing.JMenuItem();
        ControlDeCaja = new javax.swing.JMenuItem();
        ControlDeGastos = new javax.swing.JMenuItem();
        GestionDePresupuesto = new javax.swing.JMenu();
        AltaPresupuesto = new javax.swing.JMenuItem();
        PresupuestosActivos = new javax.swing.JMenuItem();
        PresupuestosGuardados = new javax.swing.JMenuItem();
        BajaPresupuesto = new javax.swing.JMenuItem();
        GestionDeUsuariosDueño = new javax.swing.JMenu();
        AltaUsuario = new javax.swing.JMenuItem();
        ModificarPrivilegios = new javax.swing.JMenuItem();
        BajaUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu de Opciones del Dueño");
        setExtendedState(MenuDeOpcionesDueño.MAXIMIZED_BOTH);
        setName("MenuDeOpcionesDueño"); // NOI18N

        CerrarSesionDueño.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        CerrarSesionDueño.setText("Cerrar Sesion");

        GestionDeClientes.setText("Gestion de Clientes");
        GestionDeClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        AltaCliente.setText("Ingresar Nuevo Cliente");
        GestionDeClientes.add(AltaCliente);

        ClientesCtaCte.setText("Clientes Cta-Cte");
        GestionDeClientes.add(ClientesCtaCte);

        ClientesMorosos.setText("Clientes Morosos");
        GestionDeClientes.add(ClientesMorosos);

        BajaCliente.setText("Eliminar Cliente");
        GestionDeClientes.add(BajaCliente);

        jMenuBar1.add(GestionDeClientes);

        GestionDeProductos.setText("Gestion de Productos");

        AltaProducto.setText("Ingresar Nuevo Producto");
        GestionDeProductos.add(AltaProducto);

        ModificarProducto.setText("Modificar Producto en Lista");
        GestionDeProductos.add(ModificarProducto);

        jMenuBar1.add(GestionDeProductos);

        OperacionesDiarias.setText("Operaciones Diarias");

        ArqueosYCierresDeCaja.setText("Arqueos y Cierres de Caja");
        OperacionesDiarias.add(ArqueosYCierresDeCaja);

        ControlDeCaja.setText("Control de Caja");
        OperacionesDiarias.add(ControlDeCaja);

        ControlDeGastos.setText("Control de Gastos");
        OperacionesDiarias.add(ControlDeGastos);

        jMenuBar1.add(OperacionesDiarias);

        GestionDePresupuesto.setText("Gestion de Presupuestos");

        AltaPresupuesto.setText("Nuevo Presupuesto");
        GestionDePresupuesto.add(AltaPresupuesto);

        PresupuestosActivos.setText("Presupuestos Activos");
        GestionDePresupuesto.add(PresupuestosActivos);

        PresupuestosGuardados.setText("Presupuestos Guardados");
        GestionDePresupuesto.add(PresupuestosGuardados);

        BajaPresupuesto.setText("Eliminar Presupuesto");
        GestionDePresupuesto.add(BajaPresupuesto);

        jMenuBar1.add(GestionDePresupuesto);

        GestionDeUsuariosDueño.setText("Gestion de Usuarios");

        AltaUsuario.setText("Nuevo Usuario");
        GestionDeUsuariosDueño.add(AltaUsuario);

        ModificarPrivilegios.setText("Modificar Privilegios");
        GestionDeUsuariosDueño.add(ModificarPrivilegios);

        BajaUsuario.setText("Eliminar Usuario");
        GestionDeUsuariosDueño.add(BajaUsuario);

        jMenuBar1.add(GestionDeUsuariosDueño);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addComponent(CerrarSesionDueño, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(CerrarSesionDueño)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("MenuDeOpcionesDelDueño");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuDeOpcionesDueño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuDeOpcionesDueño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AltaCliente;
    private javax.swing.JMenuItem AltaPresupuesto;
    private javax.swing.JMenuItem AltaProducto;
    private javax.swing.JMenuItem AltaUsuario;
    private javax.swing.JMenuItem ArqueosYCierresDeCaja;
    private javax.swing.JMenuItem BajaCliente;
    private javax.swing.JMenuItem BajaPresupuesto;
    private javax.swing.JMenuItem BajaUsuario;
    private javax.swing.JButton CerrarSesionDueño;
    private javax.swing.JMenuItem ClientesCtaCte;
    private javax.swing.JMenuItem ClientesMorosos;
    private javax.swing.JMenuItem ControlDeCaja;
    private javax.swing.JMenuItem ControlDeGastos;
    private javax.swing.JMenu GestionDeClientes;
    private javax.swing.JMenu GestionDePresupuesto;
    private javax.swing.JMenu GestionDeProductos;
    private javax.swing.JMenu GestionDeUsuariosDueño;
    private javax.swing.JMenuItem ModificarPrivilegios;
    private javax.swing.JMenuItem ModificarProducto;
    private javax.swing.JMenu OperacionesDiarias;
    private javax.swing.JMenuItem PresupuestosActivos;
    private javax.swing.JMenuItem PresupuestosGuardados;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
